meta_product_name: "Justitia"
meta_title: "Justitia - Know your rights, right now"
meta_description: "Get instant professional legal advice from lawyers all around the world. More than 100,000 lawyers ready to videochat confidentially."
meta_image: "logo.png"
twitter_account: "@JustitiaToday"
